#!/bin/bash

execute() {

    path="$1"
    period="$2"
    format="ipynb"

    for file in $path
        do
            if ls $file | cut -f 2 | grep -q $format; then
               result=$(( (`date +%s`) - (`date +%s -r "$file"`) ))
               if (( $result > $period )); then 
               jupyter nbconvert --inplace --execute $file
               fi
            fi
        done

        # To execute notebooks in parallel
        # wait
}

if [[ $# -eq 2 ]]; then
    serch='^[A-Za-z0-9\/.*"]+$' 
    if [[ $1 =~ $serch ]] && ( echo "$2" | grep -E -q '^?[0-9]+$' ); then
        execute "$1" "$2"
    fi
else
    echo 'Usage: jupyter-session-folder {"folder" period}'
fi
